# Generated by Django 3.1.4 on 2020-12-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201218_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article',
        ),
        migrations.RemoveField(
            model_name='post',
            name='news',
        ),
        migrations.AddField(
            model_name='post',
            name='article_or_news',
            field=models.CharField(choices=[('Article', 'статья'), ('news', 'новость')], default='Article', max_length=7),
        ),
    ]
